// ============================================
// CONTRAILS AI — MOCK DATA
// mock-data.js
// Matches your Google Sheet column structure.
// Replace with live data by setting CONFIG.DEMO_MODE = false
// ============================================

const MOCK_DATA = {

  gtmSignals: [
    {
      url: 'https://hivemoderationplatform.com/blog/gtm-2026',
      source_type: 'competitor_signal',
      title: 'Hive — Product/Feature Update: Expanded Moderation APIs & Real-Time Deepfake Detection',
      relevance_score: 9,
      affected_persona: 'trust_safety_lead',
      region: 'Global',
      urgency: 'medium',
      summary: 'Hive has expanded its moderation APIs to include real-time deepfake video detection with sub-100ms latency, directly competing with Contrails AI\'s core fraud detection pipeline. Their enterprise tier now includes SOC2-compliant audit logs.',
      pub_date: '2026-05-30',
      is_competitor_signal: true,
      cluster_topic: 'Competitor Intelligence',
      persona_guidance: 'Assess if Contrails AI can counter with latency benchmarks and superior accuracy on Indian-origin deepfakes.',
    },
    {
      url: 'https://thehive.ai/blog/gtm-strategy-2026',
      source_type: 'competitor_signal',
      title: 'Hive — Solidified GTM Strategy: Enterprise Trust & Safety Focus',
      relevance_score: 9,
      affected_persona: 'trust_safety_lead',
      region: 'Global',
      urgency: 'medium',
      summary: 'Hive has solidified their GTM strategy around enterprise trust and safety buyers. New case studies show 40% reduction in manual review costs. They are targeting the same FinTech and social media segments as Contrails AI.',
      pub_date: '2026-05-28',
      is_competitor_signal: true,
      cluster_topic: 'Competitor Intelligence',
      persona_guidance: 'Analyze Hive\'s enterprise positioning to identify gaps Contrails AI can exploit — particularly India/APAC coverage.',
    },
    {
      url: 'https://sensity.ai/product-update-may-2026',
      source_type: 'competitor_signal',
      title: 'Sensity — Positioning as Compliance-First Deepfake Detection Platform',
      relevance_score: 9,
      affected_persona: 'trust_safety_lead',
      region: 'Global',
      urgency: 'medium',
      summary: 'Sensity is positioning its deepfake detection platform as compliance-first, aligning with EU AI Act requirements. New partnerships with major European banks announced. Their API pricing undercuts incumbents by 30%.',
      pub_date: '2026-05-25',
      is_competitor_signal: true,
      cluster_topic: 'Competitor Intelligence',
      persona_guidance: 'Monitor Sensity\'s compliance positioning; Contrails AI should develop a compliance-ready product narrative for EU expansion.',
    },
    {
      url: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32026D1080',
      source_type: 'government_reg',
      title: 'Council Decision (EU) 2026/1080 on the conclusion of the Council of Europe Framework Convention on AI',
      relevance_score: 10,
      affected_persona: 'legal_compliance',
      region: 'EU',
      urgency: 'high',
      summary: 'The EU has formally concluded the Council of Europe Framework Convention on AI — the world\'s first legally binding international treaty on AI. This creates mandatory requirements for AI system risk assessments, transparency, and human rights safeguards for all signatories.',
      pub_date: '2026-04-21',
      is_competitor_signal: false,
      cluster_topic: 'Regulatory & Compliance',
      persona_guidance: 'Review current compliance posture against the Convention\'s transparency and human oversight requirements. High priority for sales narratives targeting EU buyers.',
    },
    {
      url: 'https://www.enisa.europa.eu/news/enisa-news/supporting-nis2',
      source_type: 'government_reg',
      title: 'ENISA: Supporting NIS2 Directive Implementation — Guidance for AI Systems',
      relevance_score: 9,
      affected_persona: 'legal_compliance',
      region: 'EU',
      urgency: 'medium',
      summary: 'ENISA has released updated guidance on NIS2 implementation specifically addressing AI-driven security systems. Organizations using AI for fraud detection must now document incident response procedures and supply chain risks.',
      pub_date: '2026-05-15',
      is_competitor_signal: false,
      cluster_topic: 'Regulatory & Compliance',
      persona_guidance: 'Review your plan for NIS2 compliance documentation. Use this as a sales angle with EU CISOs — position Contrails AI as NIS2-ready.',
    },
    {
      url: 'https://www.enisa.europa.eu/news/what-driving-cyber-investments',
      source_type: 'government_reg',
      title: "What's Driving Cybersecurity Investments in 2026: ENISA Report",
      relevance_score: 8,
      affected_persona: 'legal_compliance',
      region: 'EU',
      urgency: 'medium',
      summary: 'The ENISA NIS Investments report shows deepfake and synthetic media detection is now a top-5 cybersecurity investment priority for European enterprises. Budget allocation for AI fraud tools up 67% YoY.',
      pub_date: '2026-05-10',
      is_competitor_signal: false,
      cluster_topic: 'Regulatory & Compliance',
      persona_guidance: 'Leverage NIS2 investment data in sales decks — buyers are actively allocating budget. Include in CISO outreach messaging.',
    },
    {
      url: 'https://www.cisa.gov/sites/default/files/ABB-CISA-advisory.pdf',
      source_type: 'government_site',
      title: 'CISA Adds One Known Exploited Vulnerability — ABB Cylon Aspect',
      relevance_score: 6,
      affected_persona: 'CISO',
      region: 'US',
      urgency: 'high',
      summary: 'CISA has flagged a critical vulnerability in ABB building management systems used by financial institutions. The exploit vector includes deepfake-assisted social engineering attacks on facility access systems.',
      pub_date: '2026-05-29',
      is_competitor_signal: false,
      cluster_topic: 'Threat Intelligence',
      persona_guidance: 'Verify if the organization uses ABB systems; recommend immediate audit.',
    },
    {
      url: 'https://www.cisa.gov/advisories/fourth-frontier',
      source_type: 'government_site',
      title: 'CISA Advisory: Fourth Frontier Systems — AI-Assisted Fraud Attack Vector',
      relevance_score: 6,
      affected_persona: 'CISO',
      region: 'Global',
      urgency: 'high',
      summary: 'CISA has identified a new class of AI-assisted fraud attacks targeting financial institutions using synthetic voice and video deepfakes. Attackers bypassed KYC systems at 3 major banks in Q1 2026.',
      pub_date: '2026-05-28',
      is_competitor_signal: false,
      cluster_topic: 'Threat Intelligence',
      persona_guidance: 'Assess if existing deepfake detection systems cover synthetic voice; consider Contrails AI voice detection module.',
    },
    {
      url: 'https://www.cisa.gov/advisories/cp-plus-deepfake',
      source_type: 'government_site',
      title: 'CISA: CP Plus 8 Ch Network — Deepfake Vulnerability in Surveillance AI',
      relevance_score: 6,
      affected_persona: 'CISO',
      region: 'APAC',
      urgency: 'high',
      summary: 'A critical stored XSS vulnerability in CP Plus surveillance AI allows injection of synthetic deepfake streams, potentially defeating security monitoring in APAC financial hubs including Mumbai and Singapore.',
      pub_date: '2026-05-27',
      is_competitor_signal: false,
      cluster_topic: 'Threat Intelligence',
      persona_guidance: 'Verify if internal infrastructure uses CP Plus systems. Flag to APAC sales team as a relevant threat narrative.',
    },
    {
      url: 'https://www.cisa.gov/advisories/supply-chain-cc',
      source_type: 'government_site',
      title: 'CISA: Supply Chain CC Advisory — Synthetic Media in Vendor Impersonation',
      relevance_score: 8,
      affected_persona: 'CISO',
      region: 'Global',
      urgency: 'high',
      summary: 'A malicious VS Code extension distributing supply chain malware has been linked to a broader campaign using AI-generated deepfake executives to authorize fraudulent wire transfers. 12 enterprises affected globally.',
      pub_date: '2026-05-26',
      is_competitor_signal: false,
      cluster_topic: 'Threat Intelligence',
      persona_guidance: 'Immediately audit developer toolchain. Use this as a sales case study for Contrails AI\'s executive impersonation detection.',
    },
    {
      url: 'https://arxiv.org/abs/2406.deepfake-survey',
      source_type: 'research_paper',
      title: 'Survey: Foundation Models for Deepfake Detection — Benchmarks and Limitations',
      relevance_score: 9,
      affected_persona: 'trust_safety_lead',
      region: 'Global',
      urgency: 'medium',
      summary: 'A comprehensive survey of 47 deepfake detection methods shows that foundation model-based detectors achieve 94.2% accuracy on seen domains but drop to 61% on unseen attack types. Cross-modal (audio+video) detection remains an open research problem.',
      pub_date: '2026-05-20',
      is_competitor_signal: false,
      cluster_topic: 'Research & Technology',
      persona_guidance: 'Use cross-domain generalization gaps as a sales differentiator if Contrails AI has stronger domain adaptation.',
    },
    {
      url: 'https://iapp.org/news/a/trust-safety-summit-2026',
      source_type: 'conference',
      title: 'Trust & Safety Summit 2026 — Key Themes: Synthetic Media, AI Fraud, Regulatory Alignment',
      relevance_score: 8,
      affected_persona: 'trust_safety_lead',
      region: 'Global',
      urgency: 'medium',
      summary: 'The 2026 Trust & Safety Summit highlighted deepfake-driven fraud as the #1 concern for T&S leaders. Key sessions covered regulatory responses to synthetic media, vendor landscape review, and enterprise detection benchmarks.',
      pub_date: '2026-05-18',
      is_competitor_signal: false,
      cluster_topic: 'Conference & Events',
      persona_guidance: 'Use summit themes to personalize outreach to Trust & Safety leads. Reference specific sessions on synthetic media regulation.',
    },
  ],

  approvedBriefs: [
    {
      title: 'EU AI Act Compliance: How Contrails AI Future-Proofs Your Deepfake Detection Stack',
      cluster_topic: 'Regulatory & Compliance',
      affected_persona: 'legal_compliance',
      region: 'EU',
      summary: 'The EU AI Act (fully effective August 2026) classifies deepfake detection systems used in high-risk contexts (financial services, critical infrastructure) as high-risk AI systems requiring conformity assessments, transparency reports, and human oversight mechanisms. Contrails AI\'s audit-ready pipeline with immutable detection logs and explainable AI outputs is positioned as the go-to compliance layer for European enterprises adopting AI fraud detection.',
      persona_guidance: 'Lead with compliance costs avoided ($340K average per non-compliance incident per ENISA data). Offer a free EU AI Act readiness assessment as the CTA. Emphasize that Contrails AI logs are court-admissible.',
      approved_date: '2026-05-29',
      stage: 'Content Generation',
    },
    {
      title: "The $2.7B Deepfake Fraud Problem: Why KYC Systems Are Failing and What CISOs Are Doing About It",
      cluster_topic: 'Threat Intelligence',
      affected_persona: 'CISO',
      region: 'Global',
      summary: 'CISA\'s Q1 2026 advisories document a 340% increase in deepfake-assisted fraud targeting financial KYC systems. Three confirmed incidents involved AI-generated executive video calls authorizing fraudulent wire transfers averaging $2.7M per incident. Legacy liveness detection fails against GAN-generated faces at a 39% false negative rate. Contrails AI\'s multi-modal detection (video + audio + metadata) reduces false negatives to under 3%.',
      persona_guidance: 'Open with the CISA incident data — CISOs respond to validated threat intelligence. Follow with a live demo of Contrails AI detecting the specific attack type. Close with ROI: $2.7M average loss prevented vs. Contrails AI annual contract value.',
      approved_date: '2026-05-28',
      stage: 'LinkedIn Post',
    },
    {
      title: 'Competitor Watch: How Hive and Sensity Are Repositioning — And Where Contrails AI Wins',
      cluster_topic: 'Competitor Intelligence',
      affected_persona: 'trust_safety_lead',
      region: 'Global',
      summary: 'Hive has expanded its moderation APIs to include real-time deepfake detection but lacks coverage of Indian-language synthetic media and WhatsApp-native content. Sensity is EU-compliance focused but has no APAC presence. Contrails AI is uniquely positioned to win in the India-first, APAC-expanding market with natively trained models on Indian facial datasets and regional language audio deepfake detection.',
      persona_guidance: 'Use in competitive deal situations. Lead with Contrails AI\'s India-native advantage — no competitor has trained on APAC regional deepfake datasets at scale. Include a side-by-side accuracy benchmark on Indian-origin synthetic media.',
      approved_date: '2026-05-27',
      stage: 'Sales Deck Slide',
    },
    {
      title: 'Foundation Model Deepfake Detection: Research Gaps = Contrails AI Opportunity',
      cluster_topic: 'Research & Technology',
      affected_persona: 'trust_safety_lead',
      region: 'Global',
      summary: 'A landmark survey of 47 deepfake detection models (arXiv, May 2026) reveals that state-of-the-art foundation model detectors achieve 94.2% accuracy on familiar attack types but collapse to 61% on novel deepfake techniques. This is the cross-domain generalization problem. Contrails AI\'s continuous learning pipeline and adversarial training against emerging GAN architectures directly addresses this research gap.',
      persona_guidance: 'Target technical buyers and AI teams at prospects. Reference the arXiv paper by name — technical buyers trust peer-reviewed citations. Position Contrails AI as the production-grade solution to the research community\'s open problem.',
      approved_date: '2026-05-25',
      stage: 'X Post Thread',
    },
  ],

  stage3Queue: [
    {
      id: 'Q-001',
      title: 'EU AI Act Compliance Brief → LinkedIn Post (3-part carousel)',
      brief_ref: 'EU AI Act Compliance: How Contrails AI Future-Proofs...',
      persona: 'legal_compliance',
      format: 'LinkedIn Carousel',
      priority: 'high',
      status: 'generating',
      created_date: '2026-05-30',
      assigned_to: 'Stage 3 Pipeline',
    },
    {
      id: 'Q-002',
      title: "$2.7B Deepfake Fraud Brief → X Thread (7 tweets)",
      brief_ref: "The $2.7B Deepfake Fraud Problem...",
      persona: 'CISO',
      format: 'X / Twitter Thread',
      priority: 'high',
      status: 'pending',
      created_date: '2026-05-29',
      assigned_to: 'Stage 3 Pipeline',
    },
    {
      id: 'Q-003',
      title: 'Competitor Watch Brief → Cold Email Sequence (5 emails)',
      brief_ref: 'Competitor Watch: Hive and Sensity...',
      persona: 'trust_safety_lead',
      format: 'Email Sequence',
      priority: 'medium',
      status: 'pending',
      created_date: '2026-05-28',
      assigned_to: 'Stage 3 Pipeline',
    },
    {
      id: 'Q-004',
      title: 'Foundation Model Research Brief → Technical Blog Post',
      brief_ref: 'Foundation Model Deepfake Detection: Research Gaps...',
      persona: 'trust_safety_lead',
      format: 'Blog Post',
      priority: 'medium',
      status: 'draft',
      created_date: '2026-05-27',
      assigned_to: 'Stage 3 Pipeline',
    },
    {
      id: 'Q-005',
      title: 'EU Framework Convention Brief → Sales One-Pager',
      brief_ref: 'Council Decision (EU) 2026/1080...',
      persona: 'legal_compliance',
      format: 'Sales One-Pager',
      priority: 'high',
      status: 'approved',
      created_date: '2026-05-26',
      assigned_to: 'Design Team',
    },
    {
      id: 'Q-006',
      title: 'CISA Supply Chain Brief → CISO Outreach Deck Slide',
      brief_ref: 'CISA: Supply Chain CC Advisory...',
      persona: 'CISO',
      format: 'Deck Slide',
      priority: 'medium',
      status: 'published',
      created_date: '2026-05-25',
      assigned_to: 'Done',
    },
  ],
};
